# Site
repository: aadictive/aadictive.github.io
favicon: images/favicon.ico

# Personal info
name: Aditya Chaudhari
title: MS Computer Science Student at SUNY Binghamton
email: achaud12@binghamton.edu
website: https://aadictive.github.io/

# Social links
twitter_username: aadi_ctive
github_username:  aadictive
# dribbble_username: jekyll
facebook_username: aadi.ctive
# flickr_username: jekyll
instagram_username: aadi.ctive
linkedin_username: aadi-ctive
# pinterest_username: jekyll
# youtube_username: globalmtb
# googleplus_username: +jekyll

# About Section
# about_title: About Me
about_profile_image: images/profile.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Aditya and I'm currently pursuing my Masters in Computer Science at State University of New York at Binghamton. Prior to masters, I have worked at a company - Tellmate Helper Pvt. Ltd. as Chief Operating Officer, gaining teamwork and leadership skills.

  I am most skilled in: <mark>Signal Processing</mark>, <mark>Computer Vision & AI</mark> and <mark>Eating Pizza</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
more_title: A Little More About Me...
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in networks and computer vision engineering some of my other interests and hobbies are:
   - Trekking
   - Gaming
   - Cooking
   - Conducting Webinars

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
    - jekyll-seo-tag
