# Site
repository: aadictive/aadictive.github.io
favicon: images/favicon.ico

# Personal info
name: Aditya Chaudhari
title: MS Computer Science Student at SUNY Binghamton
email: achaud12@binghamton.edu
website: https://aadictive.github.io/

# Social links
twitter_username: aadi_ctive
github_username:  aadictive
# dribbble_username: aadi_ctive
facebook_username: aadi.ctive
# flickr_username: aadi_ctive
instagram_username: aadi.ctive
linkedin_username: aadi-ctive
# pinterest_username: aadi_ctive
# youtube_username: aadi_ctive
# googleplus_username: +aadi_ctive

# About Section
# about_title: About Me
about_profile_image: images/PortfolioPhoto.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name's Aditya and I'm currently pursuing my Masters in Computer Science at State University of New York at Binghamton. Prior to masters, I have worked at a company - Tellmate Helper Pvt. Ltd. as Chief Operating Officer, gaining teamwork and leadership skills.

  I am most skilled in: <mark>Data Science</mark>, <mark>Computer Vision & AI</mark>, <mark>Signal Processing</mark>, and <mark> Cooking Food</mark>

# Projects Section
# projects_title: Projects

# Experience Section
# experience_title: Experience

# Education Section
# educaton_title: Education

# More Section
more_title: A Little More About Me...
more_content: | # this will include new lines to allow paragraphs
  Alongside my interests in Datascience, Artificial Intelligence and Machine Learning; some of my other interests and hobbies are:
   - Trekking
   - Gaming
   - Cooking
   - Conducting Webinars (Watch them [here]())
   
  <b>-</b>

# Footer
footer_show_references: true

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
    - jekyll-seo-tag
