title: Aditya Chaudhari
subtitle: MS in Computer Science
description: >- # this means to ignore newlines until "baseurl:"
  This is a personal website developed by Aditya Chaudhari hosted on github pages. The website showcase his skills, porjects, experiences and blogs. 

url: "https://www.adityachaudhari.dev"
baseurl: ""

urls:
    - text: About Me
      url: /about
    - text: Blog
      url: /blog
    #- text: Projects
    #  url: /gallery
    - text: Videos
      url: /videos #/styleguide
    #- text: Get Started Again
    #  url: /gets-started
    # - text: Shop
    #  url : /shop
    - text: Contact Me
      url : /contact

author_logo: profile.png
author: Aditya Chaudhari
author_bio: >
 Hi, my name’s Aditya and I’m a recent MS CS graduate from the State University of New York at Binghamton. I'm Analytically driven and ambitious professional having diverse experience in Software Development, Data management, and business reporting. Proficient knowledge in Statistics, Math, Data Visualization, Data Analytics, and Analytical tools. I have had the opportunity as Chief Operating Officer at MATLAB Helper ® to work with various cross-functional & multi-cultural teams in various projects to achieve the desired results on the past.
author_email: "connect@adityachaudhari.dev"
author_location: Binghamton, New York, US
author_website_url: "https://www.adityachaudhari.dev"
typewrite-text: I am currently looking for Full-Time opportunities in Software Development

author_work_experiences:
            - company_name: Tellmate Helper Pvt. Ltd., Jaipur, India (MATLAB Helper)
              company_logo: mh.jpg
              company_url: https://matlabhelper.com/
              designation: Chief Operating Officer & MATLAB Developer
              description: |
                Worked on enhancements and customizations of business and research applications using MATLAB. Resolved critical production issues within stipulated timespan by adapting agile software methodologies. Implemented a minimalistic UI for an interactive environment aimed at providing important insights into key STEM concepts. Gained valuable experience of client interactions by collaborating with a huge team. Analyzed market for business plan and delivered pitch decks at various events along with managing company operations.
              duration: June 2018 to April 2019
              # multiple_designations: false
              # multiple_titles:
              #   - designation: MATLAB Developer Intern
              #     duration: June 2017 to June 2018
              #   - designation: MATLAB Developer
              #     duration: August 2017 to December 2017
              #   - designation: MATLAB Developer Trainee
              #     duration: June 2017 to August 2017
              visibility: true

            - company_name: Tellmate Helper Pvt. Ltd., Jaipur, India (MATLAB Helper)
              company_logo: mh.jpg
              company_url: https://matlabhelper.com/
              designation: MATLAB Developer Intern
              description: |
                Worked with developer’s team to solve client technical difficulties and accomplish solutions to projects in Neural Networks, Machine Learning, Data Analysis and Visualization. Delivered various Live coding sessions focused on MATLAB and Simulink allowing to connect with users with a more personalized touch. Collaborated with team to design a modern LMS website and add quality content for self-paced user learning experience.
              duration: June 2017 to May 2018
              visibility: true

author_education_details:
              - college_logo: bu.png
                college_name: State University of New York at Binghamton
                college_url: https://www.binghamton.edu/
                college_degree: Master of Science (MS) in Computer Science (CS)
                description: |
                  During my time at SUNY Binghamton I learnt most of my key skills that have I have taken through my career such as teamwork and working to tight deadlines. I thoroughly enjoyed my time at university and learnt a lot about healthy work life balance.
                  <br> Courses Taken as a part of coursework - CS550-Operating Systems, CS575-Design & Analysis Comp. Algorithm, CS571-Programming Languages, CS535-Introduction to Data Mining, CS565-Introduction to Artificial Intelligence, CS580-Introduction to Machine Learning.
                visibility: true
              - college_logo: kjsieit.png
                college_name: K.J. Somaiya Institute of Engineering and Information Technology
                college_url: https://kjsieit.somaiya.edu/
                college_degree: Bachelor of Enginering (BE) in Electronics & Telecommunications
                description: At KJSIEIT, I developed my skills in the field of Electronics and Telecommunications which developed my interest in Computer Vision, Robotics and AI. I was also a member and team leader of the Robotics team which earned several laurels for my college. Under my leadership, our team managed to improve our ranking from a lowly 56th place to a high of 3rd position on an all-India level within just three short years. 
                visibility: true
# Projects Template

author_project_details:
              - project_thumbnail: gamershub.png
                project_title: Gamers Hub
                project_description: A Platform built for Gamers and Game Devs
                project_url: https://gamershub.in
                visibility: false
              - project_thumbnail: hack4r.PNG
                project_title: Hack4r
                project_description: A Platform built for Hackers and Penetration Testers
                project_url: https://hack4r.com
                visibility: false

# social links
twitter_username: aadi_ctive
github_username:  aadictive
facebook_username: aadi.ctive
linkedin_username: aadi-ctive
instagram_username: aadi.ctive
medium_username: adityachaudhari


#for comments ( we got Disqus and Hyvor Commenting, uncomment the one you want to use )

# disqus_shortname: johndoe
#hyvor_talk_website_id: 735

# wakatime username (coding activity)
wakatime_username: aadictive

# mailchimp embedded form url (newsletter):
mailchimp_form_url: https://github.us18.list-manage.com/subscribe/post?u=4be95f03819c67cbcc36e0a1b&amp;id=0772c18220


# formspree (contact form)
formspree_email: xjvagaob

# syntax highlighter
markdown: kramdown
highlighter: rouge
permalink: pretty

# google analytics
#google_analytics: UA-46783401-10

# Choose what to show ( can be true or false)
show_author_work_experiences: true
show_author_education_details: true
show_author_project_details: false

# algolia search
algolia:
  application_id: D9WA1YKTRQ
  index_name: blog_posts # You can replace that with whatever name you want
  files_to_exclude: []
  nodes_to_index: 'article'
  search_only_api_key: 58ffdd7cd6c45ec1577a7fcd789b1b9a

# pagination of posts
paginate: 4
per_page: 4
paginate_path: "/blog/page/:num/"

# minify
# compress_html:
#   clippings: all
#   comments: ["<!-- ", " -->"]
#   endings: all
#   ignore:
#     envs: ['development']

# Archives
# jekyll-archives:
#   enabled:
#     - categories
#   layout: archive
#   permalinks:
#     category: '/category/:name/'

# Shop
collections:
 - products

# Gallery
defaults:
  -
    scope:
      path: "gallery"
    values:
      permalink: /:path/:basename:output_ext

# Build settings
plugins:
  - jekyll-feed
  - jekyll-paginate
  - jekyll-gist
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-algolia
  - jekyll-menus


# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
exclude:
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/
  - Gemfile
  - Gemfile.lock
  - node_modules/
  - vendor/bundle/
  - vendor/cache/
  - vendor/gems/
  - vendor/ruby/

destination: ./build
