name: Build, Deploy to beta pages

on:
  push:
    branches:
      - 'releases/**'

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Push
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
          cache: 'npm'
    
      - name: Install NPM packages
        run: npm ci

      - name: Build Project
        run: CI= npm run build
        
      - name: Upload production-ready build files
        uses: actions/upload-artifact@v2
        with:
          name: production-files
          path: ./build
    
      - name: Push to beta-pages branch
        uses: s0/git-publish-subdir-action@develop
        env:
          REPO: self
          BRANCH: beta-pages
          FOLDER: ./build
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          MESSAGE: "Build: ({sha}) {msg}" # The commit message
