name: Daily sync Master to Develop
on:
  schedule:
    - cron: '30 05 * * 0-6' # This will run everyday at 05:30 AM
  workflow_dispatch:
  
jobs:
  sync-branch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Merge master -> develop
        uses: devmasx/merge-branch@master
        with:
          type: now
          from_branch: master
          target_branch: develop
          message: Auto-merge master to develop
          github_token: ${{ secrets.GITHUB_TOKEN }}
