name: Test Git Diff command in Github Actions
on:
  workflow_dispatch:
  
jobs:
  test-example:
    runs-on: ubuntu-latest
    steps:
      - name: 'Compare'
        uses: imsamdez/actions.compare-branch@1.0.3
        with:
          base: master
          compare: develop
          github_token: ${{ secrets.GITHUB_TOKEN }}
      # Make use of the result with COMPARE_RESULT_SAME env variable
      - name: 'Result'
        run: echo Result is $COMPARE_RESULT_SAME
