name: Test Git Diff command in Github Actions
on:
  workflow_dispatch:
  
jobs:
  test-example:
    runs-on: ubuntu-latest
    steps:
      - name: Get Commit Difference Count Between Two Branches
        id: cdc
        uses: jessicalostinspace/commit-difference-action@v1.0.0
        with:
          base-branch: 'master' 
          secondary-branch: 'develop'
