name: Test Git Diff command in Github Actions
on:
  workflow_dispatch:
  
jobs:
  test-example:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Testing Step
        if: ${{git diff --color develop > foo.txt; if [ $(wc -l < foo.txt) -eq 0 ]; then false; else true; fi}}
        run: |
            echo "This workflow will run!"
