name: Test Git Diff command in Github Actions
on:
  workflow_dispatch:
  
jobs:
  test-example:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - name: Testing Step
        run: git diff --name-only origin/develop HEAD > foo.txt; if [ $(wc -l < foo.txt) -eq 0 ]; then foo='false'; else foo='true'; fi
      - name: Test
        run: echo $foo
